name: kin-3.1.3
channels:
  - conda-forge
  - bioconda 
dependencies:
  - conda-forge::python=3.8
  - conda-forge::scipy=1.8.0
  - conda-forge::numpy=1.21.1
  - conda-forge::pandas=1.3.1
  - conda-forge::numba=0.55.1
  - bioconda::pysam=0.19.0
  - bioconda::pybedtools=0.9.0
  - bioconda::samtools>=1.15
  - bioconda::bcftools>=1.15
