from plot_script import ROH_plotf, IBD_plotf, cutoff_plotf, comparison_table, comparison_plotf

infold="/mnt/diversity/divyaratan_popli/100arc/inbreeding/fastsim_gz/"
plotdata="./plotdata/"
plotimg="./plotimg/"
hmmfold="/mnt/diversity/divyaratan_popli/100arc/inbreeding/fastsim_gz/hmm_numba_incorrect_roh_i1_i1_insteadOf_i1_i2/"
Chagfold="/mnt/diversity/divyaratan_popli/100arc/inbreeding/laurits_writeup/Ch9_rem/neavar/newSim_ibd/"

#hmmdeg3="hmm_numba_incorrect_roh_i1_i1_insteadOf_i1_i2/rocNo3deg/"
rule ROHplotf:
    input:"README"
    output:"plotdata/plot_ROH.csv"
    run:
        ROH_plotf(fold=infold,outfold=plotdata)

rule ROHplot:
    input:
        infile_roh="plotdata/plot_ROH.csv",
    output:
        outfile_roh="plotimg/ROHplot.png",
    script:"Rscripts/ROHplot.R"


rule IBDplotf:
    input:"README"
    output:"plotdata/plot_IBD.csv"
    run:
        IBD_plotf(fold=infold,outfold=plotdata)

rule IBDplot:
    input:
        infile_ibd="plotdata/plot_IBD.csv",
        p1_file=infold+"contam0/inbred0/run1/coverage4/asc0/inputMode_hapProbs_fil0/hmm_parameters/p1_file.gz"
    output:
        output_ibd="plotimg/IBDplot.png"
    script:"Rscripts/IBDplot.R"

rule cutoffplotf:
    input:"README"
    output:"plotdata/contam{cnt}_inbred{inb}_model_performance_allroc_asc{asc}.csv.gz"
    run:
        cutoff_plotf(a=wildcards.asc, cnt=wildcards.cnt, inb=wildcards.inb, hmmfold=hmmfold, outfold=plotdata)

rule cutoffplot:
    input:
        infile_cut="plotdata/contam{cnt}_inbred{inb}_model_performance_allroc_asc{asc}.csv.gz"
    output:
        outfile_cut="plotimg/contam{cnt}_inbred{inb}_model_performance_allroc_asc{asc}_plot.png"
    script:"Rscripts/cutoffPlot.R"


rule comparisonplotf:
    input:"README"
    output:"plotdata/comparison_plot_data.csv.gz"
    run:
        comparison_plotf(hmmfold=hmmfold,outfold=plotdata)

rule comparisonplot:
    input:
        infile_comp="plotdata/comparison_plot_data.csv.gz"
    output:
        outfile_comp="plotimg/comparison_plot.png"
    script:"Rscripts/comparisonPlot.R"


rule Chagyrskaya:
    input:
        over=Chagfold + "overlap_fil1",
        rel=Chagfold + "hmm_numba_newA/filtered{Mfil}/merged_relatable_allLikelihoods.csv"
    output:
        outfile_rel="plotimg/fil{Mfil}_relatable_plot.png",
        outfile_over="plotimg/fil{Mfil}_overlap_plot.png"
    script: "Rscripts/kinPlot.R"


rule all:
    input:
        o1="plotimg/ROHplot.png",
        o2="plotimg/IBDplot.png",
        o3="plotimg/contam0_inbred0_model_performance_allroc_asc0_plot.png",
        o4="plotimg/comparison_plot.png",
        o5="plotimg/fil0_relatable_plot.png",
