from plot_script import ROH_plotf, IBD_plotf, cutoff_plotf, comparison_table, comparison_plotf

infold="/mnt/diversity/divyaratan_popli/100arc/inbreeding/fastsim_gz/"
outfold="./"
hmmfold="/mnt/diversity/divyaratan_popli/100arc/inbreeding/fastsim_gz/hmm_numba_incorrect_roh_i1_i1_insteadOf_i1_i2/"
#hmmdeg3="hmm_numba_incorrect_roh_i1_i1_insteadOf_i1_i2/rocNo3deg/"
rule ROHplotf:
    input:"README"
    output:"plot_ROH.csv"
    run:
        ROH_plotf(fold=infold,outfold=outfold)

rule ROHplot:
    input:
        infile_roh="plot_ROH.csv",
    output:
        outfile_roh="ROHplot.png",
    script:"ROHplot.R"


rule IBDplotf:
    input:"README"
    output:"plot_IBD.csv"
    run:
        IBD_plotf(fold=infold,outfold=outfold)

rule IBDplot:
    input:
        infile_ibd="plot_IBD.csv",
        p1_file=infold+"contam0/inbred0/run1/coverage4/asc0/inputMode_hapProbs_fil0/hmm_parameters/p1_file.gz"
    output:
        output_ibd="IBDplot.png"
    script:"IBDplot.R"

rule cutoffplotf:
    input:"README"
    output:"contam{cnt}_inbred{inb}_model_performance_allroc_asc{asc}.csv.gz"
    run:
        cutoff_plotf(a=wildcards.asc, cnt=wildcards.cnt, inb=wildcards.inb, hmmfold=hmmfold, outfold=outfold)

rule cutoffplot:
    input:
        infile_cut="contam{cnt}_inbred{inb}_model_performance_allroc_asc{asc}.csv.gz"
    output:
        outfile_cut="contam{cnt}_inbred{inb}_model_performance_allroc_asc{asc}_plot.png"
    script:"cutoffPlot.R"


rule comparisonplotf:
    input:"README"
    output:"comparison_plot_data.csv.gz"
    run:
        comparison_plotf(hmmfold=hmmfold,outfold=outfold)

rule comparisonplot:
    input:
        infile_comp="comparison_plot_data.csv.gz"
    output:
        outfile_comp="comparison_plot.png"
    script:"comparisonPlot.R"

rule all:
    input:
        o1="plot_ROH.csv",
        o2="plot_IBD.csv",
        o3="contam0_inbred0_model_performance_allroc_asc0.csv.gz",
        o4="comparison_plot_data.csv.gz",
