from plot_script import ROH_plotf, IBD_plotf, cutoff_plotf, comparison_table, comparison_plotf, IBDstates

infold="/mnt/diversity/divyaratan_popli/100arc/inbreeding/fastsim_gz_highDiversity/"
plotdata="./plotdata/"
plotimg="./plotimg/"
hmmfold="/mnt/diversity/divyaratan_popli/100arc/inbreeding/fastsim_gz_highDiversity/hmm_numba_viterbi_all_win/"
Chagfold="/mnt/diversity/divyaratan_popli/100arc/inbreeding/laurits_writeup/Ch9_rem/neavar/copied_newSim_ibd/"

#hmmdeg3="hmm_numba_incorrect_roh_i1_i1_insteadOf_i1_i2/rocNo3deg/"
runlist=list(range(1,61))
list_inds={'un':'0_1','deg5':'8_14','deg4':'1_14','deg3':'1_13','gr':'1_12','hsib':'8_9','avu':'9_12','pc':'1_8','sib':'9_10','id':'0_15'}
covlist=[4, 0.5, 0.2, 0.1, 0.05, 0.03]


rule ROHplotf:
    input:"README"
    output:"plotdata/plot_ROH.csv"
    run:
        ROH_plotf(fold=infold,outfold=plotdata)

rule ROHplot:
    input:
        infile_roh="plotdata/plot_ROH.csv",
    output:
        outfile_roh="plotimg/ROHplot.png",
    script:"Rscripts/ROHplot.R"

rule ROHlegend:
    input:
        infile_roh="plotdata/plot_ROH.csv",
    output:
            outfile_roh="inkscape/ROHlegend.png",
    script:"Rscripts/ROHlegend.R"

rule IBDplotf:
    input:"README"
    output:"plotdata/plot_IBD.csv"
    run:
        IBD_plotf(fold=infold,outfold=plotdata)

rule IBDplot:
    input:
        infile_ibd="plotdata/plot_IBD.csv",
        p1_file=infold+"contam0/inbred0/run1/coverage4/asc0/inputMode_hapProbs_fil0/hmm_parameters/p1_file.gz"
    output:
        output_ibd="plotimg/IBDplot.png"
    script:"Rscripts/IBDplot.R"

rule cutoffplotf:
    input:"README"
    output:"plotdata/contam{cnt}_inbred{inb}_model_performance_allroc_asc{asc}.csv.gz"
    run:
        cutoff_plotf(a=wildcards.asc, cnt=wildcards.cnt, inb=wildcards.inb, hmmfold=hmmfold, outfold=plotdata)

rule cutoffplot:
    input:
        infile_cut="plotdata/contam{cnt}_inbred{inb}_model_performance_allroc_asc{asc}.csv.gz"
    output:
        outfile_cut="plotimg/contam{cnt}_inbred{inb}_model_performance_allroc_asc{asc}_plot.png"
    script:"Rscripts/cutoffPlot.R"


rule comparisonplotf_supptable4:
    input:"README"
    output:
        outf="plotdata/comparison_plot_data.csv.gz",
        outs="../supplementary_info/tables/supplementary_table4.csv"

    run:
        comparison_plotf(hmmfold=hmmfold,outfold=plotdata, outs=output.outs)

rule comparisonplot:
    input:
        infile_comp="plotdata/comparison_plot_data.csv.gz"
    output:
        outfile_comp="plotimg/comparison_plot.png"
    script:"Rscripts/comparisonPlot.R"


rule Chagyrskaya:
    input:
        over=Chagfold + "overlap_fil1",
        rel=Chagfold + "hmm_new/filtered{Mfil}/merged_relatable_allLikelihoods.csv"
    output:
        outfile_rel="plotimg/fil{Mfil}_relatable_plot.png",
        outfile_over="plotimg/fil{Mfil}_overlap_plot.png"
    script: "Rscripts/kinPlot.R"


rule ibd_accuracy:
    input:
        ibd_true = expand(infold+'sanity_check/inbred0/run{RID}/coverage4/contam0/asc0/inputMode_hapProbs_fil0/{rel1}_state_all.gz', RID=runlist,rel1=[ elem for elem in list(list_inds.keys()) if elem not in ['un','pc','id','gr']]),
        ibd_pred = expand(infold+'hmm_numba_viterbi_all_win/contam0/inbred0/run{RID}/coverage{cov}/filtered0/asc0/relation_{rel1}_file/res_inphapProbs/pw_{pair}.csv.gz', RID=runlist,rel1=list(list_inds.keys()), cov=covlist, pair=list(list_inds.values()))
    output:
        outf="plotdata/plot_IBDaccuracy.csv"
    run:
        IBDstates(fold=infold, outf=output.outf, list_inds=list_inds, runlist=runlist, var='control')

rule ibd_others:
    input:
        ibd_true = expand(infold+'sanity_check/inbred0/run{RID}/coverage4/contam0/asc0/inputMode_hapProbs_fil0/{rel1}_state_all.gz', RID=runlist,rel1=[ elem for elem in list(list_inds.keys()) if elem not in ['un','pc','id','gr']]),
        ibd_pred_c = expand(infold+'hmm_numba_viterbi_all_win/contam1/inbred0/run{RID}/coverage{cov}/filtered0/asc0/relation_{rel1}_file/res_inphapProbs/pw_{pair}.csv.gz', RID=runlist,rel1=list(list_inds.keys()), cov=covlist, pair=list(list_inds.values())),
        ibd_pred_a = expand(infold+'hmm_numba_viterbi_all_win/contam0/inbred0/run{RID}/coverage{cov}/filtered0/asc2/relation_{rel1}_file/res_inphapProbs/pw_{pair}.csv.gz', RID=runlist,rel1=list(list_inds.keys()), cov=covlist, pair=list(list_inds.values())),
        ibd_pred_r = expand(infold+'hmm_numba_viterbi_all_win/contam0/inbred1/run{RID}/coverage{cov}/filtered0/asc0/relation_{rel1}_file/res_inphapProbs/pw_{pair}.csv.gz', RID=runlist,rel1=list(list_inds.keys()), cov=covlist, pair=list(list_inds.values())),

    output:
        outf_c="plotdata/plot_IBDaccuracy_cont.csv",
        outf_a="plotdata/plot_IBDaccuracy_asc.csv",
        outf_r="plotdata/plot_IBDaccuracy_roh.csv",
    run:
        IBDstates(fold=infold, outf=output.outf_c, list_inds=list_inds, runlist=runlist, var='c')
        IBDstates(fold=infold, outf=output.outf_a, list_inds=list_inds, runlist=runlist, var='a')
        IBDstates(fold=infold, outf=output.outf_r, list_inds=list_inds, runlist=runlist, var='r')

rule ibd_accuracy_plot:
    input:
        inf="plotdata/plot_IBDaccuracy.csv"
    output:
        outf="plotimg/plot_IBDaccuracy.png"
    script: "Rscripts/IBD_accuracyPlot.R"


rule ibd_accuracy_plot_others:
    input:
        inf_c="plotdata/plot_IBDaccuracy_cont.csv",
        inf_a="plotdata/plot_IBDaccuracy_asc.csv",
        inf_r="plotdata/plot_IBDaccuracy_roh.csv",
    output:
        outf="plotimg/plot_IBDaccuracy_others_supp.png",

    script: "Rscripts/supp_IBD.R"


rule all:
    input:
        o1="plotimg/ROHplot.png",
        o2="plotimg/IBDplot.png",
        o3="plotimg/contam0_inbred0_model_performance_allroc_asc0_plot.png",
        o4="plotimg/comparison_plot.png",
        o5="plotimg/fil0_relatable_plot.png",
        o6="plotimg/plot_IBDaccuracy.png"
