from delta_functions import *
from beta_bnds import *
from forcedROH import *
from supplementary_scripts import suppTable2, misscontam_plotf

datafolder="/mnt/diversity/divyaratan_popli/100arc/inbreeding/fastsim_gz_highDiversity/"
datafolder_alt="/mnt/diversity/divyaratan_popli/100arc/inbreeding/fastsim_gz/"
paramfolder="/mnt/diversity/divyaratan_popli/100arc/inbreeding/fastsim_gz/transitions/"
hbdfolder="/mnt/diversity/divyaratan_popli/100arc/inbreeding/fastsim_gz_highDiversity/hbd_hmm/"
Chagfold="/mnt/diversity/divyaratan_popli/100arc/inbreeding/laurits_writeup/Ch9_rem/neavar/newSim_ibd/"
lcfold="/mnt/diversity/divyaratan_popli/100arc/inbreeding/laurits_writeup/Ch9_rem/neavar/"
deg2fold="/mnt/diversity/divyaratan_popli/100arc/inbreeding/fastsim_gz_highDiversity/"
bronze_age_folder="/mnt/diversity/divyaratan_popli/100arc/inbreeding/bronze_age_newSim/"
missCfold="/mnt/diversity/divyaratan_popli/review_sim/hmm_numba/miss_contam/"

inds=list(range(17))
instates=[0,1,2]
runlist=list(range(1,61))

mind_list=[10]
mcont_list=[0.5,1.5,2.5,3.5,4.5,5.5]
covlist=[4, 0.5, 0.2, 0.1, 0.05]


listf=[]
for i, l1 in enumerate(inds):
    for l2 in inds[(i+1):]:
        s = '%s_%s' %(str(l1).strip("['']"), str(l2).strip("['']"))
        listf.append(s)


rule get_delta:
    input:
        pfile=datafolder+"contam0/inbred0/run1/coverage4/asc0/inputMode_hapProbs_fil0/hmm_parameters/p1_file.gz",
        dfile=datafolder+"contam0/inbred0/run1/coverage4/asc0/inputMode_hapProbs_fil0/merged_wind.csv.gz",
        tfile=datafolder+"contam0/inbred0/run1/coverage4/asc0/inputMode_hapProbs_fil0/merged_wint.csv.gz",
        Afile=paramfolder+"transition_matrix_{rel}.csv",



    output:
        deltafile="datafiles/contam0_inbred0_run1_coverage4_asc0_inputMode_hapProbs_fil0_delta_{listind}_{rel}.csv.gz"


    run:
        l=wildcards.listind
        print(l)
        i1=l.split('_')[0]
        i2=l.split('_')[1]
        print(i1,i2)

        pairf1=hbdfolder+"contam0/inbred0/run1/coverage4/filtered0/asc0_res/gamma_hapProbs/pw_%s.csv.gz" %(i1)
        pairf2=hbdfolder+"contam0/inbred0/run1/coverage4/filtered0/asc0_res/gamma_hapProbs/pw_%s.csv.gz" %(i2)

        p1thresh=datafolder+"contam0/inbred0/run1/coverage4/asc0/inputMode_idhapProbs_fil1/id_remHighdiv_total.csv"

        hmm(difffile=input.dfile, totalfile=input.tfile, listind=wildcards.listind,
                        listf=np.array(listf), targets=np.array(inds),pfile=input.pfile,
                        Afile=input.Afile, deltafile=output.deltafile,
                        upA='un', pairf1=pairf1, pairf2=pairf2,
                        p1thresh=p1thresh, thresh=10, instates=instates)



rule binom_plot:
    input:
        dfile=datafolder + "contam0/inbred0/run1/coverage4/asc0/inputMode_hapProbs_fil0/merged_wind.csv.gz",
        tfile=datafolder + "contam0/inbred0/run1/coverage4/asc0/inputMode_hapProbs_fil0/merged_wint.csv.gz",
        p1file=datafolder + "contam0/inbred0/run1/coverage4/asc0/inputMode_hapProbs_fil0/hmm_parameters/p1_file.gz",
        del0="datafiles/contam0_inbred0_run1_coverage4_asc0_inputMode_hapProbs_fil0_delta_0_1_un.csv.gz",
        del1="datafiles/contam0_inbred0_run1_coverage4_asc0_inputMode_hapProbs_fil0_delta_0_8_pc.csv.gz",
        del2="datafiles/contam0_inbred0_run1_coverage4_asc0_inputMode_hapProbs_fil0_delta_0_15_id.csv.gz",
    output:
        binomplot="plots/binom.png"
    script:"Rscripts/binom.R"


rule Chagyrskaya:
    input:
        over=Chagfold + "overlap_fil1",
        rel=Chagfold + "hmm_numba_newA/filtered{Mfil}/read/READ_results"
    output:
        outfile_rel="plots/fil{Mfil}_read_plot.png",
        outfile_over="plots/fil{Mfil}_overlap_plot.png"
    script: "Rscripts/readPlot.R"


rule lcMLkin:
    input:
        lcres=lcfold + "noCh12_9mar_newmodel/lcMLkin/output.relate",
        likf=Chagfold + "hmm_numba/filtered0/merged_relatable_allLikelihoods.csv",
        kinf=Chagfold + "hmm_numba/filtered0/IBDstates_allLikelihoods.csv"

    output:
        outplot="plots/lcPlot.pdf"
    script:"Rscripts/lcPlot.R"


rule degree2_plot:
    input:
        fnames=expand(deg2fold+"1M_win/hmm_numba/contam0/inbred0/run{r}/coverage4/filtered0/asc0/IBDstates_allLikelihoods_inphapProbs.csv.gz", r=runlist),
    output:
        outplot="plots/degree2_10Mwin.png",
    script:"Rscripts/degree2_cluster.R"

rule variance_bnd_data:
    input:
        pfile=datafolder+"contam{cnt}/inbred{inb}/run{RID}/coverage{cov}/asc{asc}/inputMode_{inpMode}_fil{Mfil}/hmm_parameters/p1_file.gz",
        dfile=datafolder+"contam{cnt}/inbred{inb}/run{RID}/coverage{cov}/asc{asc}/inputMode_{inpMode}_fil{Mfil}/remHighdiv_diff.csv.gz",
        tfile=datafolder+"contam{cnt}/inbred{inb}/run{RID}/coverage{cov}/asc{asc}/inputMode_{inpMode}_fil{Mfil}/remHighdiv_total.csv.gz",
        Afile=paramfolder+"transition_matrix_{rel}.csv"
    output:
        B1file="dataf/contam{cnt}_inbred{inb}_run{RID}_coverage{cov}_asc{asc}_inputMode_{inpMode}_fil{Mfil}_B1file_{listind}_rel{rel}",
        B2file="dataf/contam{cnt}_inbred{inb}_run{RID}_coverage{cov}_asc{asc}_inputMode_{inpMode}_fil{Mfil}_B2file_{listind}_rel{rel}",
        xnew1file="dataf/contam{cnt}_inbred{inb}_run{RID}_coverage{cov}_asc{asc}_inputMode_{inpMode}_fil{Mfil}_xnew1file_{listind}_rel{rel}",
        xnew2file="dataf/contam{cnt}_inbred{inb}_run{RID}_coverage{cov}_asc{asc}_inputMode_{inpMode}_fil{Mfil}_xnew2file_{listind}_rel{rel}",
        resfile1="dataf/contam{cnt}_inbred{inb}_run{RID}_coverage{cov}_asc{asc}_inputMode_{inpMode}_fil{Mfil}_resfile1_{listind}_rel{rel}",
        resfile2="dataf/contam{cnt}_inbred{inb}_run{RID}_coverage{cov}_asc{asc}_inputMode_{inpMode}_fil{Mfil}_resfile2_{listind}_rel{rel}",
        betaplot="plots/contam{cnt}_inbred{inb}_run{RID}_coverage{cov}_asc{asc}_inputMode_{inpMode}_fil{Mfil}_pair{listind}_rel{rel}_betaplot1.png",

    run:
        l=wildcards.listind
        print(l)
        i1=l.split('_')[0]
        i2=l.split('_')[1]
        print(i1,i2)

        cov=str(wildcards.cov)
        cnt=str(wildcards.cnt)
        inb=str(wildcards.inb)
        run=str(wildcards.RID)
        asc=str(wildcards.asc)
        inpMode=str(wildcards.inpMode)
        fil=str(wildcards.Mfil)

        #parameters I used:
        #cov=0.2
        #cnt=0
        #inb=1
        #run=57
        #asc=0
        #inpMode=hapProbs
        #fil=0

        pairf1=hbdfolder+"contam%s/inbred%s/run%s/coverage%s/filtered%s/asc%s_res/gamma_%s/pw_%s.csv.gz" %(cnt,inb,run,cov,fil,asc,inpMode,i1)
        pairf2=hbdfolder+"contam%s/inbred%s/run%s/coverage%s/filtered%s/asc%s_res/gamma_%s/pw_%s.csv.gz" %(cnt,inb,run,cov,fil,asc,inpMode,i2)

        p1thresh=datafolder+"contam%s/inbred%s/run%s/coverage%s/asc%s/inputMode_id%s_fil1/id_remHighdiv_total.csv" %(cnt,inb,run,cov,asc,inpMode)

        plot_betas(dfile=input.dfile, tfile=input.tfile, pair=wildcards.listind,
                        listf=np.array(listf), libraries=np.array(inds),pfile=input.pfile,
                        Afile=input.Afile, B1file=output.B1file, B2file=output.B2file, xnew1file=output.xnew1file,
                        xnew2file=output.xnew2file, rel=wildcards.rel, pairf1=pairf1, pairf2=pairf2,
                        p1thresh=p1thresh, thresh=10, instates=instates,res1file=output.resfile1, res2file=output.resfile2, betaplot=output.betaplot)


rule plot_emission:
    input:
        p1f=datafolder+"contam{cnt}/inbred{inb}/run{RID}/coverage{cov}/asc{asc}/inputMode_{inpMode}_fil{Mfil}/hmm_parameters/p1_file.gz",
        dfile=datafolder+"contam{cnt}/inbred{inb}/run{RID}/coverage{cov}/asc{asc}/inputMode_{inpMode}_fil{Mfil}/remHighdiv_diff.csv.gz",
        tfile=datafolder+"contam{cnt}/inbred{inb}/run{RID}/coverage{cov}/asc{asc}/inputMode_{inpMode}_fil{Mfil}/remHighdiv_total.csv.gz",
        B1file="dataf/contam{cnt}_inbred{inb}_run{RID}_coverage{cov}_asc{asc}_inputMode_{inpMode}_fil{Mfil}_B1file_{listind}_rel{rel}",
        B2file="dataf/contam{cnt}_inbred{inb}_run{RID}_coverage{cov}_asc{asc}_inputMode_{inpMode}_fil{Mfil}_B2file_{listind}_rel{rel}",
        xnew1="dataf/contam{cnt}_inbred{inb}_run{RID}_coverage{cov}_asc{asc}_inputMode_{inpMode}_fil{Mfil}_xnew1file_{listind}_rel{rel}",
        xnew2="dataf/contam{cnt}_inbred{inb}_run{RID}_coverage{cov}_asc{asc}_inputMode_{inpMode}_fil{Mfil}_xnew2file_{listind}_rel{rel}",
    output:
        outf="plots/contam{cnt}_inbred{inb}_run{RID}_coverage{cov}_asc{asc}_inputMode_{inpMode}_fil{Mfil}_pair{listind}_rel{rel}_emissions_bnds.png"
    script:"Rscripts/emission_bnds.R"


rule plot_forcedROH:
    input:
        p1f=datafolder_alt+"contam{cnt}/inbred{inb}/run{RID}/coverage{cov}/asc{asc}/inputMode_{inpMode}_fil{Mfil}/hmm_parameters/p1_file.gz",
        dfile=datafolder_alt+"contam{cnt}/inbred{inb}/run{RID}/coverage{cov}/asc{asc}/inputMode_id{inpMode}_fil{Mfil}/id_remHighdiv_diff.csv.gz",
        tfile=datafolder_alt+"contam{cnt}/inbred{inb}/run{RID}/coverage{cov}/asc{asc}/inputMode_id{inpMode}_fil{Mfil}/id_remHighdiv_total.csv.gz",
        chrmf=datafolder_alt+"contam{cnt}/inbred{inb}/run{RID}/coverage{cov}/asc{asc}/inputMode_id{inpMode}_fil{Mfil}/id_chrm.csv.gz"
    output:
        outplot="plots/contam{cnt}_inbred{inb}_run{RID}_coverage{cov}_asc{asc}_inputMode_{inpMode}_fil{Mfil}_ind{ind}_forced_roh.png"
    run:

        plotbetas(dfile=input.dfile, tfile=input.tfile, ind=wildcards.ind, chrmf=input.chrmf,
        p1file=input.p1f, upA='initial', targets=inds, outplot=output.outplot)

rule supplementary_table23:
    input:
        resultsf='/home/divyaratan_popli/Documents/bronze_age_data/aax6219_Mittnik_SM_TableS10_kinship_inference.xlsx',
        kinf=bronze_age_folder + "hmm_numba_corrAsim_grSib_replaced/filtered0/merged_relatable_allLikelihoods.csv"
    output:
        outf2="tables/supplementary_table2.csv",
        outf3="tables/supplementary_table3.csv"
    run:
        suppTable2(resultsf=input.resultsf, kinf=input.kinf, outf2=output.outf2, outf3=output.outf3)

rule egplot1:
    input:
        p1f=bronze_age_folder + "hmm_parameters_fil0/p1_file",
        datadf=bronze_age_folder + "mergedwin_remHighdiv_fil0/pw_diff.csv",
        datatf=bronze_age_folder + "mergedwin_remHighdiv_fil0/pw_total.csv",
        chrmf=bronze_age_folder + "mergedwin_fil0/merged_chrm.csv"
    output:
        outimg="plots/egplot1.png"
    script:"Rscripts/egplot1.R"

rule egplot2:
    input:
        p1f=bronze_age_folder + "hmm_parameters_fil0/p1_file",
        datadf=bronze_age_folder + "mergedwin_remHighdiv_fil0/pw_diff.csv",
        datatf=bronze_age_folder + "mergedwin_remHighdiv_fil0/pw_total.csv",
        chrmf=bronze_age_folder + "mergedwin_fil0/merged_chrm.csv"
    output:
        outimg="plots/egplot2.png"
    script:"Rscripts/egplot2.R"

rule contam_miss_file:
    input:
        kin=expand(missCfold+"output/missC{mcont}_{mind}/contam{cnt}/inbred{inb}/model_performance_{folder}/coverage{cov}/asc{asc}/filtered{Mfil}_cut{cutoff}.csv.gz", cnt=1, inb=0, folder="allLikelihoods_inphapProbs", cov=covlist, Mfil=0, asc=0, cutoff=1.0, mcont=mcont_list, mind=mind_list),
        pc_sib=expand(missCfold+"output/missC{mcont}_{mind}/contam{cnt}/inbred{inb}/pc_sib_performance_allLikelihoods_inphapProbs/coverage{cov}/asc{asc}/filtered0_cut{cut_pcsib}/pc_sib.csv.gz", cut_pcsib=1,cov=covlist,cnt=1,inb=0,asc=0, mind=mind_list, mcont=mcont_list)
    output:
        outf="dataf/contam1_inbred0_model_performance_allLikelihoods_inphapProbs_asc0.csv"
    run:
        misscontam_plotf(outf=output.outf,covs=covlist,ctlist=mcont_list)
rule contam_miss_plot:
    input:
        infile="dataf/contam1_inbred0_model_performance_allLikelihoods_inphapProbs_asc0.csv"
    output:
        outfile="plots/contam_missspecification.png"
    script: "Rscripts/misscontam_plot.R"
